/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.configuration.*;
import org.apache.flink.streaming.api.datastream.*;
import org.apache.flink.streaming.api.environment.*;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    static void helloWorld() {
        String version = System.getProperty("java.version");
        String location = System.getProperty("java.home");
        System.out.println("Java Version: " + version);
        System.out.println("JVM Location: " + location);
        System.out.println(new App().getGreeting());
    }

    public static void main(String[] args) throws Exception {
        helloWorld();
        final StreamExecutionEnvironment env =
            StreamExecutionEnvironment.createLocalEnvironmentWithWebUI(
                new Configuration()
            );
        DataStream<Long> ds = env.fromSequence(0, 1L).setParallelism(10);
        System.out.println(ds.getId());
        ds = ds.map(
            new MapFunction<Long, Long>() {
                @Override
                public Long map(Long value) throws Exception {
                    Thread.sleep(1000);
                    return value * 2;
                }
            }
        );
        ds.print();
        env.execute();
    }
}
