/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class MainTest {

    @Test
    void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(
            classUnderTest.getGreeting(),
            "app should have a greeting"
        );
    }
}
